spring:
  datasource:
    url: jdbc:h2:mem:provadb
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: alessio.alemix41@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true